package mip.restaurantfx;
import jakarta.persistence.EntityManager;
import jakarta.persistence.NoResultException;
import jakarta.persistence.TypedQuery;

import java.util.List;
import java.util.Optional;

public class UserRepository {

    private EntityManager getEntityManager() {
        return PersistenceManager.getInstance().getEntityManagerFactory().createEntityManager();
    }

    public Optional<User> login(String username, String password) {
        EntityManager em = getEntityManager();
        try {
            TypedQuery<User> query = em.createQuery(
                    "SELECT u FROM User u WHERE u.username = :user AND u.password = :pass", User.class);
            query.setParameter("user", username);
            query.setParameter("pass", password);

            return Optional.of(query.getSingleResult());
        } catch (NoResultException e) {
            return Optional.empty();
        } finally {
            em.close();
        }
    }

    public void save(User user) {
        EntityManager em = getEntityManager();
        try {
            em.getTransaction().begin();
            em.persist(user);
            em.getTransaction().commit();
        } finally {
            em.close();
        }
    }

    public Optional<User> findByUsername(String username) {
        EntityManager em = getEntityManager();
        try {
            return Optional.of(
                    em.createQuery("SELECT u FROM User u WHERE u.username = :user", User.class)
                            .setParameter("user", username)
                            .getSingleResult()
            );
        } catch (NoResultException e) {
            return Optional.empty();
        } finally {
            em.close();
        }
    }

    public boolean deleteByUsername(String username) {
        EntityManager em = getEntityManager();
        try {
            em.getTransaction().begin();

            User managed;
            try {
                managed = em.createQuery("SELECT u FROM User u WHERE u.username = :user", User.class)
                        .setParameter("user", username)
                        .getSingleResult();
            } catch (NoResultException e) {
                em.getTransaction().rollback();
                return false;
            }
            em.remove(managed);

            em.getTransaction().commit();
            return true;
        } catch (Exception e) {
            if (em.getTransaction().isActive()) em.getTransaction().rollback();
            throw e;
        } finally {
            em.close();
        }
    }

    public List<User> findByRole(User.Role role) {
        EntityManager em = getEntityManager();
        try {
            return em.createQuery(
                            "SELECT u FROM User u WHERE u.rol = :rol ORDER BY u.nume", User.class)
                    .setParameter("rol", role)
                    .getResultList();
        } finally {
            em.close();
        }
    }

    public List<User> getAllStaff() {
        return findByRole(User.Role.STAFF);
    }

    public long count() {
        EntityManager em = getEntityManager();
        try {
            return em.createQuery("SELECT COUNT(u) FROM User u", Long.class).getSingleResult();
        } finally {
            em.close();
        }
    }
    public int deleteAutoGeneratedStaff() {
        EntityManager em = getEntityManager();
        try {
            em.getTransaction().begin();

            List<User> auto = em.createQuery(
                            "SELECT u FROM User u WHERE u.rol = :rol AND (" +
                                    "u.username LIKE 'staff1\\_%' ESCAPE '\\' OR " +
                                    "u.username LIKE 'staff2\\_%' ESCAPE '\\' OR " +
                                    "u.nume LIKE 'Ospatar 1%' OR " +
                                    "u.nume LIKE 'Ospatar 2%'" +
                                    ")",
                            User.class)
                    .setParameter("rol", User.Role.STAFF)
                    .getResultList();

            int count = 0;
            for (User u : auto) {
                em.remove(u);
                count++;
            }

            em.getTransaction().commit();
            return count;
        } catch (Exception e) {
            if (em.getTransaction().isActive()) em.getTransaction().rollback();
            throw e;
        } finally {
            em.close();
        }
    }
}